### PR TITLE
Add a file for South St. Paul, MN

### PR DESCRIPTION
**Pull request by sfgdpm**
The purpose of this PR is to add a hometown file for South St. Paul, MN :ice_hockey: 

Some ? that I want you all to help me answer:
1. If you've been to South St. Paul, what did you do?  What did you think of it?
1. If you have kids, what kind of things do they like to do at night?
1. What kind of food do you like?

### CODE REVIEW

**Comment by SFGDJQM** [comment]
I have never been to South St. Paul, and I don't have kids, but I like pizza.

**Comment by sfgdpm** [comment]
> but I like pizza

Same

**Comment by sfgdpm** [comment]
This PR resolves #4

**Review by SFGDJQM — APPROVED** [review]
This thing is ready to :ship: :shipit:!

**Pull request merged**
